#!/bin/sh

exec > "$HOME/.dwl.log" 2>&1

export XDG_CURRENT_DESKTOP=wlroots
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=wlroots

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland,x11

export __GLX_VENDOR_LIBRARY_NAME=nvidia
#export GBM_BACKEND=nvidia-drm
#export __NV_PRIME_RENDER_OFFLOAD=1
#export __VK_LAYER_NV_optimus=NVIDIA_only
#export LIBVA_DRIVER_NAME=nvidia
#export NVD_BACKEND=direct
#export WLR_DRM_NO_MODIFIERS=1
#export WLR_NO_HARDWARE_CURSORS=1

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
fi

(
    sleep 1
    wlr-randr --output eDP-2 --mode 1920x1080@144.028Hz --pos 0,0 \
              --output HDMI-A-1 --mode 1920x1080@60Hz --pos 1920,0
    
    pipewire &
    wireplumber &
    pipewire-pulse &
    swww-daemon &
    Throne -tray &
    mako &
    udiskie &
    /usr/libexec/polkit-mate-authentication-agent-1 &
) &

exec dbus-run-session sh -c 'slstatus -s | dwl'
